spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dd_anonymous?useSSL=false&serverTimezone=UTC
    username: root
    password:
mybatis:
  config-location: classpath:mybatis.xml
debug: true
server:
  port: 8888
