
# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'base'
  username: 'root'
  password: '1122qq'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""
